# Numpy tutorial

In [1]:
import numpy

In [2]:
a=numpy.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.shape

(5,)

In [39]:
a.dtype

dtype('int32')

In [5]:
b=numpy.array([11,22,33,44,55])

In [6]:
b

array([11, 22, 33, 44, 55])

In [7]:
b.shape

(5,)

In [9]:
c=numpy.array([34,89,56])

In [10]:
c

array([34, 89, 56])

In [11]:
d=numpy.array([44,89,4,99,23])

In [12]:
d

array([44, 89,  4, 99, 23])

In [13]:
import numpy as np 

In [14]:
a=np.array([45,78,34])

In [15]:
a

array([45, 78, 34])

In [16]:
b=np.array([12,8,9,3,4,5,6,77])

In [17]:
b

array([12,  8,  9,  3,  4,  5,  6, 77])

In [18]:
b.shape

(8,)

In [19]:
a

array([45, 78, 34])

In [20]:
a.min()

34

In [21]:
a.max()

78

In [22]:
b

array([12,  8,  9,  3,  4,  5,  6, 77])

In [40]:
b.dtype

dtype('int32')

In [23]:
b.min()

3

In [24]:
b.max()

77

In [25]:
b.shape

(8,)

two dimensional numpy array

In [27]:
c=np.array([[1,2],[3,4]])

In [28]:
c

array([[1, 2],
       [3, 4]])

In [29]:
c.shape

(2, 2)

In [30]:
c.min()

1

In [31]:
c.max()

4

In [32]:
c.size

4

In [33]:
c.dtype

dtype('int32')

In [34]:
f=np.array([12,13,14,15,16,17])

In [35]:
f

array([12, 13, 14, 15, 16, 17])

In [37]:
f.dtype

dtype('int32')

In [38]:
f.itemsize

4

In [41]:
f.size

6

In [42]:
p=np.array([[12,13],[14,15]])

In [43]:
p

array([[12, 13],
       [14, 15]])

In [44]:
p.shape

(2, 2)

In [45]:
p.size

4

In [46]:
p.itemsize

4

In [47]:
p.min()

12

In [49]:
p.max()

15

In [50]:
p.dtype

dtype('int32')

In [51]:
k=np.array([[11,12,13],[14,15,16],[17,18,19]])

In [52]:
k

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [53]:
k.shape

(3, 3)

In [54]:
k.size

9

In [55]:
k.itemsize

4

In [56]:
k.dtype

dtype('int32')

In [57]:
h=np.array([[100,200,300],[400,500,600]])

In [58]:
h

array([[100, 200, 300],
       [400, 500, 600]])

In [59]:
h.shape

(2, 3)

In [60]:
m=np.array([[1,22.3,67],[3,8,5]])

In [61]:
m

array([[ 1. , 22.3, 67. ],
       [ 3. ,  8. ,  5. ]])

In [63]:
m=np.array([[1,22.3,67],[3,8,5]],dtype='int32')

In [64]:
m

array([[ 1, 22, 67],
       [ 3,  8,  5]])

In [65]:
m=np.array([[1,22.3,67],[3,8,5]],dtype='float64')

In [66]:
m

array([[ 1. , 22.3, 67. ],
       [ 3. ,  8. ,  5. ]])

In [68]:
m=np.array([[1,22.3,67],[3,8,5]],dtype='float32')

In [69]:
m

array([[ 1. , 22.3, 67. ],
       [ 3. ,  8. ,  5. ]], dtype=float32)

In [70]:
type(m)

numpy.ndarray

In [71]:
m.dtype

dtype('float32')

In [72]:
m.ndim

2

In [73]:
m.shape

(2, 3)

In [74]:
m

array([[ 1. , 22.3, 67. ],
       [ 3. ,  8. ,  5. ]], dtype=float32)

In [75]:
m.reshape(3,2)

array([[ 1. , 22.3],
       [67. ,  3. ],
       [ 8. ,  5. ]], dtype=float32)

In [76]:
m.size

6

In [77]:
m.itemsize

4

In [98]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [99]:
s=np.arange(6)

In [100]:
s

array([0, 1, 2, 3, 4, 5])

In [101]:
s.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
s.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [104]:
k=np.arange(35)

In [105]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [106]:
k.reshape(7,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [108]:
k.reshape(5,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [109]:
k.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [78]:
a=np.array([[4,5,6],[6,7,8],[3,7,9]])

In [79]:
a

array([[4, 5, 6],
       [6, 7, 8],
       [3, 7, 9]])

In [ ]:
# task write numpy array of 4 rows 3 colums

# hint p=np.array([,,],[,,],[,,])

# p.shape

In [80]:
# give shape in dimension : row and colums
a.shape

(3, 3)

In [81]:
# give the count of number of elements
a.size

9

In [82]:
# give the number of bytes/memory occupied by each elements
a.itemsize

4

In [83]:
# give the datatype
a.dtype

dtype('int32')

In [84]:
a.min()

3

In [85]:
# give the memory address
a.data

In [87]:
a=np.array([[1,2],[3,4],[5,6]],dtype='float64')
#c1=np.array([[1,2],[3,4],[5,6]]

a
#c1

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [88]:
a.dtype

dtype('float64')

In [89]:
#number of dimension # 2 stands for rows and colums
a.ndim

2

In [90]:
# gives number of bytes : it is floiat datatype hence it takes 8 bytes to store
a.itemsize

8

In [91]:
a.shape

(3, 2)

In [92]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [93]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [94]:
x=np.arange(15)

In [95]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [96]:
a=x.reshape(3,5)

In [97]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
import numpy

In [6]:
import numpy as np

x=np.array([[1.5,2,3],[4,5,6]],dtype='float32')

In [7]:
x

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [8]:
ra=np.array([[34,78,89],[22,33,77]])
ra

array([[34, 78, 89],
       [22, 33, 77]])

In [9]:
# ravel operation where you can convert one numpy array into a single row i.e ravel
print(ra.ravel())

[34 78 89 22 33 77]


In [10]:
import numpy as np
x=np.array([[1.5,2,3],[4,5,6]],dtype='int32')
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#(start,end,skip or jump)

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [17]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [19]:
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [20]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [21]:
c=a-b
print(c)

[20 29 38 47]


In [22]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [23]:
b=np.random.random([2,3])

In [24]:
b

array([[0.29780516, 0.13040598, 0.02867365],
       [0.00420885, 0.46226051, 0.04625683]])

In [25]:
c=np.ones([2,3])

In [26]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
d=b+c
d

array([[1.29780516, 1.13040598, 1.02867365],
       [1.00420885, 1.46226051, 1.04625683]])

Universal Functions:
    

In [28]:
B=np.arange(3)

In [29]:
B

array([0, 1, 2])

In [30]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [31]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [32]:
c=np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

Indexing,Slicing,and lterating

In [33]:
a=np.arange(10)

In [34]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[2]

2

In [36]:
a[2:5]

array([2, 3, 4])

In [37]:
a[-1]

9

In [38]:
a[-2]

8

In [39]:
a[-3]

7

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[-4:]

array([6, 7, 8, 9])

In [42]:
a[-4:-2]

array([6, 7])

In [43]:
d2=np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
d2[5:] #Slicing from 5th index till end of the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
d3 = np.array([np.nan,1,2,3,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

The random module provides nice function to generate random numbers (and also statistical distribusions )
of any given shape rand function will generate any number between 0 to 1

In [48]:
np.random.rand(2,2) #uniform distribusions --> similar loke random

array([[0.37728675, 0.23032324],
       [0.87865497, 0.56102873]])

rand will generate any number for normal distribusion in the given dimension format

In [49]:
np.random.rand(2,3)

array([[0.23088592, 0.77281292, 0.73306211],
       [0.40241114, 0.01557366, 0.5735582 ]])

# PANDAS FINAL

Pandas is a Python library for data analysis, pandas is fast, powerful, flexible and easy to use open source data analysis 
and manipulation tool, built on top of the python programming language.

In [4]:
import pandas as pd

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

In [ ]:
a=pd.Series([1,2,3,4,5])

In [52]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [53]:
b=pd.Series([10,20,30,40])

In [54]:
b

0    10
1    20
2    30
3    40
dtype: int64

In [55]:
c=pd.Series([12,13,14,15,16])

In [56]:
c

0    12
1    13
2    14
3    15
4    16
dtype: int64

In [59]:
c=pd.Series([12,13,14,15,16],index=[1,2,3,4,5])
c

1    12
2    13
3    14
4    15
5    16
dtype: int64

In [60]:
c=pd.Series([12,13,14,15,16],index=[100,200,300,400,500])

In [61]:
c

100    12
200    13
300    14
400    15
500    16
dtype: int64

In [62]:
c=pd.Series([12,13,14,15,16],index=[100,200,300,400,500],dtype='int32')
c

100    12
200    13
300    14
400    15
500    16
dtype: int32

In [63]:
c=pd.Series([12,13,14,15,16],index=[100,200,300,400,500],dtype='float32')
c

100    12.0
200    13.0
300    14.0
400    15.0
500    16.0
dtype: float32

In [1]:
dict1={'id':1,'name':'AAA'}

p=pd.Series(dict1)
p

NameError: name 'pd' is not defined